const menuList = [
    {
        title:"首页",
        key:"/admin/home",
    },
    {
        title:"UI",
        key:"/admin/ui",
        children:[
            {
                title:"按钮",
                key:"/admin/ui/buttons",
            },
            {
                title:"弹框",
                key:"/admin/ui/modals",
            },
            {
                title:"Loading",
                key:"/admin/ui/loading",
            },
        ]
    },
    {
        title:"表单",
        key:"/admin/ui",
        children:[
            {
                title:"按钮",
                key:"/admin/ui/buttons",
            },
            {
                title:"弹框",
                key:"/admin/ui/modals",
            },
            {
                title:"Loading",
                key:"/admin/ui/loading",
            },
        ]
    },
    {
        title:"表格",
        key:"/admin/ui",
        children:[
            {
                title:"按钮",
                key:"/admin/ui/buttons",
            },
            {
                title:"弹框",
                key:"/admin/ui/modals",
            },
            {
                title:"Loading",
                key:"/admin/ui/loading",
            },
        ]
    },
    {
        title:"富文本",
        key:"/admin/home",
    },
    {
        title:"城市管理",
        key:"/admin/home",
    },
    {
        title:"订单管理",
        key:"/admin/home",
    },
    {
        title:"员工管理",
        key:"/admin/home",
    },
    {
        title:"车辆地图",
        key:"/admin/home",
    },
    {
        title:"图标",
        key:"/admin/ui",
        children:[
            {
                title:"按钮",
                key:"/admin/ui/buttons",
            },
            {
                title:"弹框",
                key:"/admin/ui/modals",
            },
            {
                title:"Loading",
                key:"/admin/ui/loading",
            },
        ]
    },
    {
        title:"权限设置",
        key:"/admin/home",
    },
];

export default menuList